// apps/docs/design/example/segmented-control.tsx
// eslint-disable-next-line
'use client'

import React from 'react'
import dynamic from 'next/dynamic'

// import { GdsSegment } from '@sebgroup/green-react/core/segment'
// import { GdsSegmentedControl } from '@sebgroup/green-react/core/segmented-control'

const GdsSegment = dynamic(
  () => import('@sebgroup/green-react/src/core/segment'),
  {
    ssr: false,
  },
)

const GdsSegmentedControl = dynamic(
  () => import('@sebgroup/green-react/src/core/segmented-control'),
  {
    ssr: false,
  },
)

const SegmentedControl = () => (
  <>
    <GdsSegmentedControl size="small" value="1">
      <GdsSegment value="1">Segmented</GdsSegment>
      <GdsSegment value="2">Control</GdsSegment>
    </GdsSegmentedControl>
  </>
)

export default SegmentedControl

// apps/angular-lib-dev/src/app/segmented-control/segmented-control.component.ts
import { Component } from '@angular/core'
// eslint-disable-next-line
import { SegmentedControl } from '@sebgroup/green-angular'
import { Observable, of } from 'rxjs'

@Component({
  templateUrl: './segmented-control.component.html',
  styleUrls: ['./segmented-control.component.css'],
})
export class SegmentedControlComponent {
  $controls: Observable<Array<SegmentedControl>> = of([
    { url: './option-a', text: 'Option A' },
    { url: './option-b', text: 'Option B' },
  ])
}

<h3 class="mb-4">Segmented control with routes</h3>
<ngg-segmented-control [$controls]="$controls"></ngg-segmented-control>
<router-outlet></router-outlet>
