// libs/angular/src/lib/dropdown/dropdown.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChild,
  ElementRef,
  EventEmitter,
  Inject,
  Injector,
  Input,
  OnInit,
  Output,
  ViewChild,
} from '@angular/core'
import {
  ControlValueAccessor,
  NgControl,
  NG_VALUE_ACCESSOR,
} from '@angular/forms'

import { NggDropdownOptionDirective } from './dropdown-option.directive'
import { NggDropdownButtonDirective } from './dropdown-button.directive'

import {
  GdsDropdown,
  GdsOption,
} from '@sebgroup/green-core/components/dropdown'
import { registerTransitionalStyles } from '@sebgroup/green-core/transitional-styles'

export type CompareWith<T = any> = (o1: T, o2: T) => boolean
export type SearchFilter<T = any> = (search: string, value: T) => boolean
export type DropdownPlacements = 'bottom-start' | 'top-start'
export interface DropdownTexts {
  select?: string
  selected?: string
  placeholder?: string
  searchPlaceholder?: string
  close?: string
  optionsDescription?: string
}
export interface DropdownOption {
  label?: string
  value?: any
  selected?: boolean
  heading?: boolean
  [key: string]: any
}

@Component({
  selector: 'ngg-dropdown',
  templateUrl: 'dropdown.component.html',
  styleUrls: ['dropdown.component.scss'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: NggDropdownComponent,
      multi: true,
    },
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NggDropdownComponent implements ControlValueAccessor, OnInit {
  @Input() id?: string
  @Input() texts?: DropdownTexts
  @Input() loop?: boolean = false
  @Input() display = 'label'
  @Input() useValue = 'value'
  @Input() label?: string
  @Input() valid?: boolean
  @Input() invalid?: boolean
  @Input() compareWith?: CompareWith
  @Input() searchFilter?: SearchFilter
  @Input() syncPopoverWidth?: boolean
  @Input() size?: 'small' | 'medium'
  @Input() hideLabel?: boolean
  @Input() maxHeight?: number

  /** @deprecated */
  @Input() fixedPlacement?: DropdownPlacements

  //
  @Input() set options(value: DropdownOption[] | undefined) {
    this._options = value
    this.texts = {
      ...this.texts,
      select: this.displayTextByValue(this._value),
    }
  }
  get options(): DropdownOption[] | undefined {
    return this._options
  }
  private _options: DropdownOption[] | undefined

  //
  @Input() set multiSelect(value: string | boolean) {
    this._multiSelect = this.convertToBoolean(value)
  }
  get multiSelect(): boolean {
    return this._multiSelect
  }
  private _multiSelect = false

  //
  @Input() set searchable(value: string | boolean) {
    this._searchable = this.convertToBoolean(value)
  }
  get searchable(): boolean {
    return this._searchable
  }
  private _searchable = false

  //
  @Input() set value(newValue: any) {
    if (!this.options) return

    this._value = newValue

    this.texts = {
      ...this.texts,
      select: this.displayTextByValue(this._value),
    }
  }
  get value(): any {
    return this._value
  }
  private _value: DropdownOption | DropdownOption[] | undefined

  //
  get selectedOption() {
    return Array.isArray(this.value)
      ? this.value.map((v: any) => this.optionByValue(v))
      : this.optionByValue(this.value)
  }

  onChangeFn?: (value: unknown) => void
  onTouchedFn?: () => void

  @Output() readonly valueChange: EventEmitter<any> = new EventEmitter<any>()
  @Output() readonly touched: EventEmitter<boolean> =
    new EventEmitter<boolean>()

  @ContentChild(NggDropdownOptionDirective)
  customOption?: NggDropdownOptionDirective

  @ContentChild(NggDropdownButtonDirective)
  customButton?: NggDropdownButtonDirective

  @ViewChild('gdsDropdown', { static: false }) gdsDropdown?: ElementRef

  public onValueChange: (event: Event) => void = (event) => {
    const target = event.target as GdsDropdown<DropdownOption>
    this._value = target.value

    this.texts = {
      ...this.texts,
      select: this.displayTextByValue(this._value),
    }

    this.onChangeFn?.(this.value)
    this.valueChange.emit(this.value)

    this._cdr.detectChanges()
  }

  get control(): NgControl | undefined {
    return this.injector.get(NgControl)
  }

  constructor(
    @Inject(Injector) private injector: Injector,
    private _cdr: ChangeDetectorRef,
  ) {
    registerTransitionalStyles()
  }

  ngOnInit(): void {
    if (!this._value) {
      if (this.multiSelect)
        this._value = this.options
          ?.filter((o) => o.selected === true)
          ?.map((o) => o[this.useValue])
      else
        this._value = this.options?.find((o) => o.selected === true)?.[
          this.useValue
        ]

      this.texts = {
        ...this.texts,
        select: this.displayTextByValue(this._value),
      }
    }

    this.texts = {
      close: this.texts?.close ?? 'Close',
      optionsDescription: this.texts?.optionsDescription ?? 'Options',
      placeholder: this.texts?.placeholder ?? 'Select',
      searchPlaceholder: this.texts?.searchPlaceholder ?? 'Search',
      selected: this.texts?.selected ?? 'selected',
      select: this.displayTextByValue(this._value),
    }
  }

  writeValue(value: any): void {
    this.value = value
    this._cdr.detectChanges()
  }

  registerOnChange(fn: () => unknown): void {
    this.onChangeFn = fn
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedFn = fn
  }

  // These adapter functions are used to maintain backwards compatibility with the old interface
  compareWithAdapter = (o1: any, o2: any) => {
    const compareFn = this.compareWith || ((a, b) => a === b)
    return compareFn(o1, o2)
  }
  searchFilterAdapter = (q: string, o: GdsOption) => {
    if (this.searchFilter) return this.searchFilter(q, o.value)
    else
      return ((q: string, o: GdsOption) =>
        o.innerHTML.toLowerCase().includes(q.toLowerCase()))(q, o)
  }

  private convertToBoolean(value: string | boolean): boolean {
    return (
      value === '' || value === 'true' || value.toString() === 'true' || false
    )
  }

  private optionByValue = (value: any) => {
    return this.options?.find((o) => o[this.useValue] === value)
  }

  private displayTextByValue = (value: any) => {
    if (!Array.isArray(value))
      return (
        this.optionByValue(value)?.[this.display] ||
        (this.texts?.placeholder ?? 'Select')
      )

    const displayValues = value.map(
      (v) => this.optionByValue(v)?.[this.display],
    )
    return displayValues?.length > 2
      ? `${displayValues.length} ${this.texts?.selected} `
      : displayValues?.join(', ') || (this.texts?.placeholder ?? 'Select')
  }
}

<div class="form-group">
  <span class="label" *ngIf="label" [id]="toggler?.attributes?.id + '_label'">{{
    label
  }}</span>
  <button
    [attr.aria-labelledby]="label ? toggler?.attributes?.id + '_label' : null"
    [attr.aria-describedby]="
      formInfo?.textContent && (formInfo?.textContent?.length ?? 0 > 0)
        ? toggler?.attributes?.id + '_info'
        : null
    "
    type="button"
    #togglerRef
    [id]="toggler?.attributes?.id"
    [attr.aria-haspopup]="toggler?.attributes?.['aria-haspopup']"
    [attr.aria-expanded]="toggler?.attributes?.['aria-expanded']"
    [attr.aria-owns]="toggler?.attributes?.['aria-owns']"
    [tabindex]="toggler?.attributes?.tabIndex"
    [style]="toggler?.attributes?.style"
    [class]="toggler?.classes"
    (click)="handler?.toggle()"
    [class.is-valid]="valid"
    [class.is-invalid]="invalid"
  >
    <ng-container
      *ngTemplateOutlet="
        customButton?.templateRef && !multiSelect && selectedOption
          ? customButton!.templateRef
          : defaultButton;
        context: { option: selectedOption }
      "
    ></ng-container>
  </button>
  <span
    class="form-info"
    #formInfo
    [attr.id]="toggler?.attributes?.id + '_info'"
    ><ng-content select="[data-form-info]"></ng-content
  ></span>
  <div
    #listboxRef
    [id]="listbox?.attributes?.id"
    [attr.role]="listbox?.attributes?.role"
    [attr.aria-activedescendant]="
        listbox?.attributes?.['aria-activedescendant']
      "
    [tabindex]="listbox?.attributes?.tabIndex"
    [style]="listbox?.attributes?.style"
    [class]="listbox?.classes"
  >
    <button
      type="button"
      class="close m-4 m-sm-2 d-block d-sm-none"
      (click)="handler?.close()"
    >
      <span class="sr-only">{{ dropdown?.texts?.close }}</span>
      <i></i>
    </button>
    <ul role="listbox" *ngIf="!dropdown?.isMultiSelect">
      <ng-container *ngTemplateOutlet="searchInput"></ng-container>
      <li
        *ngFor="
          let option of dropdown?.options;
          let index = index;
          trackBy: trackByKey
        "
        [id]="option.attributes.id"
        [attr.role]="option.attributes.role"
        [attr.aria-selected]="option.attributes['aria-selected']"
        [style]="option.attributes.style"
        [class]="option.classes"
        (click)="handler?.select(option)"
      >
        <ng-container
          *ngTemplateOutlet="
            customOption?.templateRef
              ? customOption!.templateRef
              : defaultOption;
            context: { option: option, index: index }
          "
        ></ng-container>
      </li>
    </ul>
    <div *ngIf="dropdown?.isMultiSelect" class="sg-fieldset-container">
      <ng-container *ngTemplateOutlet="searchInput"></ng-container>
      <!--TODO: Improve checkboxes in dropdown angular-->
      <fieldset
        #fieldsetRef
        [attr.aria-describedby]="fieldset?.attributes?.id"
        role="listbox"
        tabIndex="-1"
        aria-multiselectable="true"
      >
        <legend class="sr-only" [id]="fieldset?.attributes?.id">Options</legend>
        <label
          class="form-control"
          [attr.role]="option.attributes.role"
          [id]="option.attributes.id"
          [attr.aria-selected]="option.attributes['aria-selected']"
          [class]="option.classes"
          *ngFor="
            let option of dropdown?.options;
            let index = index;
            trackBy: trackByKey
          "
        >
          <input
            type="checkbox"
            (change)="handler?.select(option, false)"
            [checked]="option.selected"
            tabIndex="-1"
          />
          <ng-container
            *ngTemplateOutlet="
              customOption?.templateRef
                ? customOption!.templateRef
                : defaultOption;
              context: { option: option, index: index }
            "
          ></ng-container>
          <i></i>
        </label>
      </fieldset>
    </div>
  </div>
</div>

<ng-template #defaultButton let-selected="selected">
  <span>{{ dropdown?.texts?.select }}</span>
</ng-template>

<ng-template #defaultOption let-option="option">
  {{ option[dropdown!.display] }}
</ng-template>

<ng-template #searchInput>
  <input
    *ngIf="dropdown?.isSearchable"
    [id]="toggler?.attributes?.id + '_search-input'"
    type="search"
    (input)="search($event)"
    placeholder="{{ dropdown?.texts?.searchPlaceholder }}"
    class="rounded-0 rounded-top border-0 border-bottom border-info"
  />
</ng-template>

// libs/react/src/lib/dropdown/dropdown.tsx
import React from 'react'
import { createComponent } from '@lit/react'

import {
  GdsDropdown,
  GdsOption,
} from '@sebgroup/green-core/components/dropdown/index.js'
import { getScopedTagName } from '@sebgroup/green-core/scoping'
import { registerTransitionalStyles } from '@sebgroup/green-core/transitional-styles'
import { CoreMenuHeading } from '../context-menu/context-menu'

export type CompareWith<T = any> = (o1: T, o2: T) => boolean
export type SearchFilter<T = any> = (search: string, value: T) => boolean
export type DropdownPlacements = 'bottom-start' | 'top-start'
export type OnChange<T = any> = (value: T) => void

export type IndicatorType = 'success' | 'error' | 'info'
export type ValidatorType = 'Required' | 'Email'

export interface ValidatorRules {
  type: ValidatorType
  custom?: () => string | undefined
}

export interface IValidator {
  message: string
  indicator: IndicatorType
  rules?: ValidatorRules
}

export interface DropdownArgs {
  compareWith?: CompareWith
  display?: string // option key to display
  id?: string
  informationLabel?: string
  label?: string
  multiSelect?: boolean
  options: DropdownOption[]
  searchFilter?: SearchFilter
  searchable?: boolean
  texts?: DropdownTexts
  useValue?: string // option key to use as value
  validator?: IValidator
  value?: any

  /** Force width of the popover to match trigger */
  syncPopoverWidth?: boolean

  /** Size of the dropdown trigger */
  size?: 'small' | 'medium'

  /** Hide the label */
  hideLabel?: boolean

  /** Max height of the dropdown */
  maxHeight?: number

  /** Whether to disable the mobile styles */
  disableMobileStyles?: boolean

  /** Event handler for when the dropdown is opened or closed */
  onGdsUiState?: (e: CustomEvent) => void
}
export interface DropdownTexts {
  placeholder?: string
}
export interface DropdownOption {
  label?: string
  value?: any
  selected?: boolean
  heading?: boolean
  [key: string]: any
}

registerTransitionalStyles()

export const CoreDropdown = createComponent({
  tagName: getScopedTagName('gds-dropdown'),
  elementClass: GdsDropdown,
  events: { onChange: 'change', onGdsUiState: 'gds-ui-state' },
  react: React,
})

export const CoreOption = createComponent({
  tagName: getScopedTagName('gds-option'),
  elementClass: GdsOption,
  react: React,
})

export interface DropdownProps extends DropdownArgs {
  onChange?: OnChange,
  required?: boolean,
}

export const Dropdown = ({
  compareWith,
  display = 'label',
  id,
  informationLabel,
  label,
  multiSelect,
  onChange,
  options,
  searchFilter,
  searchable,
  texts,
  useValue = 'value',
  validator,
  value,
  syncPopoverWidth,
  disableMobileStyles,
  onGdsUiState,
  required,
  ...props
}: DropdownProps) => {
  const handleOnChange = (e: any) => {
    if ('value' in e.detail) {
      onChange?.(e.detail.value)
    }
  }

  // These adapter functions are used to maintain backwards compatibility with the old interface
  const compareWithAdapter = (o1: DropdownOption, o2: DropdownOption) => {
    const compareFn = compareWith || ((a, b) => a === b)
    return compareFn(o1, o2)
  }

  const searchFilterAdapter = (q: string, o: GdsOption) => {
    if (searchFilter) return searchFilter(q, o.value[useValue])
    else
      return ((q: string, o: GdsOption) =>
        o.innerHTML.toLowerCase().includes(q.toLowerCase()))(q, o)
  }

  return (
    <div className="form-group">
      <CoreDropdown
        id={id}
        label={label}
        searchable={searchable}
        multiple={multiSelect}
        onChange={handleOnChange}
        invalid={validator?.indicator === 'error'}
        compareWith={compareWithAdapter}
        value={value}
        searchFilter={searchFilterAdapter}
        syncPopoverWidth={syncPopoverWidth}
        size={props.size}
        hideLabel={props.hideLabel}
        maxHeight={props.maxHeight}
        disableMobileStyles={disableMobileStyles}
        required={required}
        onGdsUiState={(e: Event) => onGdsUiState?.(e as CustomEvent)}
      >
        {informationLabel && <span slot="sub-label">{informationLabel}</span>}
        {validator && <span slot="message">{validator.message}</span>}
        <CoreOption isPlaceholder aria-hidden>
          {texts?.placeholder || 'Select'}
        </CoreOption>
        {options.map((option) => {
          if (option.heading) {
            return (
              <CoreMenuHeading key={option.label}>
                {option[display]}
              </CoreMenuHeading>
            )
          }
          return (
            <CoreOption key={option[useValue]} value={option[useValue]}>
              {option[display]}
            </CoreOption>
          )
        })}
      </CoreDropdown>
    </div>
  )
}

export default Dropdown
