// packages/green-react/src/card/Card.tsx
import { FC, ReactNode } from 'react'
import Button from '../button'

export interface CardProps {
  children?: ReactNode
  headline?: string
  buttons?: typeof Button[]
}

const Card: FC<CardProps> = ({ children, headline, buttons }) => {
  return (
    <section className="card">
      <div className="card-body">
        { headline && <h2>{headline}</h2> }
        <p>{children}</p>
        {buttons && <footer>{buttons}</footer> }
      </div>
    </section>
  )
}

export default Card

// packages/chlorophyll-storybook/src/stories/css/card/Card.svelte
<script>
  /**
   * A Card Component
   * @component
   */

  /**
   * Card contents
   */
  export let headline = '';
  export let body = '';
  export let buttonText1 = '';
  export let buttonText2 = '';
</script>

<section class="card">
  <div class="card-body">
    <h2>{headline}</h2>
    <p>{body}</p>
    <footer>
      <button>{buttonText1}</button>
      <a class="button primary" href="#">{buttonText2}</a>
    </footer>
  </div>
</section>
