// libs/react/src/lib/form/button.tsx
import { ButtonHTMLAttributes, MouseEventHandler, ReactNode } from 'react'
import { ButtonType, ButtonVariant } from '@sebgroup/extract'

/* eslint-disable-next-line */
export interface ButtonProps {
  children?: ReactNode
  type?: ButtonType
  variant?: ButtonVariant
  active?: boolean
  onClick?: MouseEventHandler<HTMLButtonElement>
}

export function Button({
  children,
  variant,
  onClick,
  active = false,
  type = 'button',
}: ButtonProps) {
  const props: ButtonHTMLAttributes<HTMLButtonElement> = { type }
  const classNames: string[] = []
  if (variant) classNames.push(variant)
  if (active) classNames.push('active')

  if (classNames.length) props.className = classNames.join(' ')
  if (onClick) props.onClick = onClick

  return <button {...props}>{children}</button>
}

export default Button

// libs/angular/src/lib/button/button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  Input
} from '@angular/core'
import { ButtonType, ButtonVariant } from '@sebgroup/extract';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: '[ngg-button]',
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NggButtonComponent {

  @Input() variant?: ButtonVariant;
  @Input() size?: ButtonType;

  @HostBinding('class') get classes(): string {
    return [this.variant, this.size ? 'size-' + this.size : false].filter(Boolean).join(" ")
  }
}
