// libs/angular/src/lib/slider/slider.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnInit,
  Output,
  SimpleChanges,
} from '@angular/core'
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms'
import {
  getSliderTrackBackground,
  randomId,
  sliderColors,
} from '@sebgroup/extract'

interface SliderStyle {
  background?: string
}

@Component({
  selector: 'ngg-slider',
  templateUrl: './slider.component.html',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: NggSliderComponent,
      multi: true,
    },
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NggSliderComponent implements ControlValueAccessor, OnInit {
  @Input() name = `${randomId()}-slider`
  @Input() min = 0
  @Input() max = 100
  @Input() step = 1
  @Input() label = ''
  @Input() instruction = ''
  @Input() placeholder = ''
  @Input() errorMessage = ''
  @Input() hasTextbox = false
  @Input() disabled = false
  @Input() value = 0
  @Output() sliderChange = new EventEmitter<number>()
  @Output() sliderTouch = new EventEmitter<boolean>()
  onChangeFn?: (val: number) => void
  onTouchedFn?: VoidFunction
  style: SliderStyle = {}

  ngOnInit(): void {
    this.setTrackBackground()
  }

  onBlur(): void {
    this.sliderTouch.emit(true)
    this.onTouchedFn && this.onTouchedFn()
  }

  handleChange(): void {
    this.value = this.value ?? 0
    this.setTrackBackground()
    this.sliderChange.emit(this.value)
    this.onChangeFn && this.onChangeFn(this.value)
  }

  setTrackBackground(): void {
    if (this.disabled) {
      this.style.background = sliderColors.disabled
      return
    }

    const percent = ((this.value - this.min) / (this.max - this.min)) * 100
    this.style.background = getSliderTrackBackground(percent)
  }

  /** control value accessor functions */
  writeValue(val: number): void {
    if (this.value !== val) {
      this.value = val ?? 0
      this.handleChange()
    }
  }

  registerOnChange(fn: any): void {
    this.onChangeFn = fn
  }

  registerOnTouched(fn: any): void {
    this.onTouchedFn = fn
  }
}

<div *ngIf="!!label" class="gds-slider-label-container">
  <div>
    <label [attr.for]="name" [attr.id]="name + '-label'">{{ label }}</label>
    <p *ngIf="!!instruction">{{ instruction }}</p>
  </div>
  <ng-container *ngIf="hasTextbox">
    <ng-container *ngIf="!!unitLabel">
      <div class="gds-group gds-group--small gds-group-border gds-group-focus">
        <ng-container *ngTemplateOutlet="inputField"></ng-container>
        <span class="gds-form-text">{{ unitLabel }}</span>
      </div>
    </ng-container>
    <ng-container *ngIf="!unitLabel">
      <ng-container *ngTemplateOutlet="inputField"></ng-container>
    </ng-container>
  </ng-container>
</div>

<input
  type="range"
  [attr.id]="name"
  [attr.name]="name"
  [attr.min]="min"
  [attr.max]="max"
  [attr.step]="step"
  [disabled]="disabled"
  [(ngModel)]="value"
  [ngStyle]="style"
  [attr.aria-valuenow]="value"
  (blur)="onBlur()"
  (input)="handleChange()"
/>

<p *ngIf="!!errorMessage" class="gds-slider-error-info">
  {{ errorMessage }}
</p>

<ng-template #inputField>
  <input
    type="text"
    inputmode="numeric"
    pattern="[0-9]*"
    [(ngModel)]="value"
    class="gds-input small"
    [class.is-invalid]="!!errorMessage"
    [attr.name]="name"
    [attr.id]="name + '-textbox'"
    [attr.placeholder]="placeholder"
    [attr.aria-labelledby]="name + '-label'"
    [attr.enterkeyhint]="enterkeyhint"
    [disabled]="disabled"
    (blur)="onBlur()"
    (input)="handleChange()"
  />
</ng-template>

// libs/react/src/lib/slider/slider.tsx
import React from 'react'

import {
  getSliderTrackBackground,
  randomId,
  sliderColors,
} from '@sebgroup/extract'
import { SliderProps } from '../../types'

const InputWrapper = ({
  children,
  unitLabel,
}: {
  children: React.ReactNode
  unitLabel?: string
}) => (
  <>
    {unitLabel ? (
      <div className="group group-border group-focus">
        {children}
        <span className="form-text">{unitLabel}</span>
      </div>
    ) : (
      children
    )}
  </>
)

const minMaxFormatFn = (value: number, unit?: string) => {
  if (unit) return `${value} ${unit}`
  return value.toString()
}

export function Slider({
  name = `${randomId()}-slider`,
  value,
  defaultValue,
  min = 0,
  max = 100,
  minMaxFormat = minMaxFormatFn,
  showMinMax = false,
  step = 1,
  label,
  instruction,
  errorMessage,
  hasTextbox = false,
  unitLabel,
  disabled = false,
  onChange,
  enableClamping = true,
  onClamp,
  enterKeyHint,
}: SliderProps) {
  const [background, setBackground] = React.useState<string>()
  const [sliderValue, setSliderValue] = React.useState<number | undefined>(
    value ?? defaultValue,
  )
  const [inputFieldValue, setInputFieldValue] = React.useState<string>(
    sliderValue + '',
  )

  React.useLayoutEffect(() => {
    if (disabled) {
      setBackground(sliderColors.disabled)
      return
    }

    let percent = 0
    if (sliderValue !== undefined)
      percent = ((sliderValue - min) / (max - min)) * 100

    setBackground(getSliderTrackBackground(percent))
  }, [disabled, sliderValue])

  const clamp = (unclamped: number | undefined | string): number => {
    if (!enableClamping) return Number(unclamped)

    if (typeof unclamped === 'string') unclamped = Number(unclamped)
    if (!unclamped || Number.isNaN(unclamped)) return min

    const clamped = Math.min(Math.max(min, unclamped), max)
    if (clamped !== unclamped && onClamp) onClamp(unclamped)

    return clamped
  }

  const setNumValue = (value: number | undefined | string) => {
    if (value === '') value = min
    const unclamped = Number(value)
    const clamped = clamp(unclamped)
    setSliderValue(clamped)
    return [unclamped, clamped]
  }

  React.useEffect(() => {
    setNumValue(value)
  }, [value])

  const handleChange = (value: string) => {
    const [unclamped, clamped] = setNumValue(value)
    setInputFieldValue(unclamped + '')
    if (onChange) onChange(clamped)
  }

  const handleInputFieldChange = (value: string, shouldClamp = false) => {
    handleChange(value)
    if (value === '') setInputFieldValue('')
    else if (shouldClamp) setInputFieldValue(clamp(value) + '')
  }

  return (
    <>
      <div className="gds-slider-label-container">
        <div>
          {label && (
            <>
              <label htmlFor={name} id={`${name}-label`}>
                {label}
              </label>
              {instruction && <p>{instruction}</p>}
            </>
          )}
        </div>
        {hasTextbox && (
          <InputWrapper unitLabel={unitLabel}>
            <input
              type="text"
              inputMode="numeric"
              pattern="[0-9]*"
              value={inputFieldValue}
              id={`${name}-textbox`}
              name={name}
              aria-labelledby={`${name}-label`}
              enterKeyHint={enterKeyHint}
              className={errorMessage ? 'is-invalid' : ''}
              disabled={disabled}
              onChange={(e) => handleInputFieldChange(e.currentTarget.value)}
              onKeyDown={(e) =>
                e.key === 'Enter' &&
                handleInputFieldChange(e.currentTarget.value, true)
              }
              onBlur={(e) =>
                handleInputFieldChange(e.currentTarget.value, true)
              }
              min={min}
              max={max}
              onInvalid={(e) => {
                e.preventDefault()
              }}
            />
          </InputWrapper>
        )}
      </div>
      <input
        type="range"
        value={sliderValue || 0}
        id={name}
        name={name}
        min={min}
        max={max}
        step={step}
        disabled={disabled}
        onChange={(e) => handleChange(e.currentTarget.value)}
        style={{
          background,
        }}
      />
      {showMinMax && (
        <div className="gds-slider-min-max">
          <div>{minMaxFormat(min, unitLabel)}</div>
          <div>{minMaxFormat(max, unitLabel)}</div>
        </div>
      )}
      {errorMessage && <p className="gds-slider-error-info">{errorMessage}</p>}
    </>
  )
}

export default Slider
